name: Test Autorec

on:
  pull_request:
    paths:
      - "module/autorec.json"
  push:
    paths:
      - "module/autorec.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3

      - name: Test
        run: node .github/check-autorec.js
